artifact_location: file:C:/Users/MaesakD/Documents/Learning/MLOps/project_setup/project_setup/Model_Tracking/0
creation_time: 1745792165312
experiment_id: '0'
last_update_time: 1745792165312
lifecycle_stage: active
name: Default
