input_file_path: data/raw/fetal_health.csv
train_raw_path: data/processed_data/train.csv       # Correct path to your raw training data
test_raw_path: data/processed_data/test.csv  # Correct raw data path
output_file_path: data/processed_data        # Processed data save path
test_ratio: 0.2                              # Test data size
random_state: 42 