artifact_location: file:C:/Users/MaesakD/Documents/Learning/MLOps/project_setup/project_setup/Model_Tracking/877749782740625521
creation_time: 1745792165344
experiment_id: '877749782740625521'
last_update_time: 1745792165344
lifecycle_stage: active
name: LightGBM Model Training
