artifact_uri: file:C:/Users/MaesakD/Documents/Learning/MLOps/project_setup/project_setup/Model_Tracking/877749782740625521/8f4cae9ed27b4db5b3635af1f99527dc/artifacts
end_time: 1745829183709
entry_point_name: ''
experiment_id: '877749782740625521'
lifecycle_stage: active
run_id: 8f4cae9ed27b4db5b3635af1f99527dc
run_name: blushing-ray-847
run_uuid: 8f4cae9ed27b4db5b3635af1f99527dc
source_name: ''
source_type: 4
source_version: ''
start_time: 1745829159103
status: 3
tags: []
user_id: MaesakD
